# ===== SERVER =====
server.port=8080

# ===== H2 IN-MEMORY DATABASE =====
spring.datasource.url=jdbc:h2:mem:kittydb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JPA =====
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# ===== AI =====
groq.api.key=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

# ===== APP =====
spring.application.name=kittyassistant
# --- ??? ???????????? ????????? ?????? ??? ???? ---

# Google OAuth2 (?????? ???? ??????)
spring.security.oauth2.client.registration.google.client-id=177253023967-6lb7h2fo7pbv01qdv381b87oqd2c61mn.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Spring Batch ? ?? ????????? ????????????? ??? ??????
spring.batch.job.enabled=false

# H2 Console (???? ?? ????????)
spring.h2.console.enabled=true
spring.jpa.show-sql=false